### ISSUE TITLE
Preshape does not work with Next.js

### ISSUE THREAD

**Issue by xeoneux** [HHogg/preshape#3]
As the components import their CSS files right inside the component, it is incompatible with the latest Next.js version.

One possible solution is to remove the import statement from the component and instead create a new file to import it.

Example:
```ts
// Button/Button.tsx
... everything minus the import './Button.css`'
```

```ts
// Button/index.tsx
import ./Button.css
export ./Button.tsx
```

```ts
// index.ts
export { default as Button, ButtonProps } from './Button'
```

**Comment by HHogg** [comment]
Hey @xeoneux, I understand, I encountered this exact issue with NextJS before on another project. I'll take a look at this and see what options there are, but I expect a single separate CSS file is the only way forward.

_Apologies too, I didn't get a notification that this issue was raised so have just stumbled on it_

Just curious what you are using Preshape for?

**Comment by HHogg** [comment]
I'm closing this. I don't use NextJS for any of my projects, and this library exists primarily for my projects.
